export const TRACKER_EVENTS = {
  OPPONENT_RANK: 'opponent-rank',
  NUM_CPUS: 'num-cpus',
  DB_IMPORT_FINISH: 'db-import-finish',
  DB_IMPORT_TABLE_START: 'db-import-table-start',
  DB_IMPORT_START: 'db-import-start',
  DB_IMPORT_ROW: 'db-import-row',
  META: 'meta',
  SEASONS: 'seasons',
  INITIALIZED_DB: 'initialized-db',
  LOAD_START: 'load-start',
  PARSE_START: 'parse-start',
  LOAD_FINISH: 'load-finish',
  CANCELLED_INIT: 'cancelled-init',
  FREED_WORKER: 'freed-worker',
  PERSIST_FINISH: 'persist-finish',
  GAME_START: 'game-start',
  GAME_END: 'game-end',
  PLAYER_PERCENTS: 'player-percents',
  PARSED_FILE: 'parsed-file',
  CHARACTER_NOTES: 'character-notes',
}